# fly.toml app configuration file generated for wdcc-youth-of-orakei on 2025-05-31T22:17:56+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wdcc-youth-of-orakei'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
