name: Fly Deploy Staging

on:
  push:
    branches:
      - ORAKEI-Anton-Test-Deploy

jobs:
  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_MEMBERS_ID: ${{ secrets.NOTION_MEMBERS_ID }}
          ANTON: ${{ secrets.ANTON }}
          AntonVar: ${{ vars.ANTONVAR }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.staging.toml
        
     
    
      

