name: Fly Deploy Staging

on:
  push:
    branches:
      - ORAKEI-Anton-Test-Deploy

jobs:
  test-vars:
    name: Test Var
    runs-on: ubuntu-latest
    environment: Notion
    steps:
      - name: Test ANTON Secret
        run: echo "the name is ${{ secrets.ANTON }}"

      - name: Test NOTION_MEMBERS_ID Secret
        run: echo "Notion Members ID is ${{ secrets.NOTION_MEMBERS_ID }}"

      - name: Test NOTION_TOKEN Secret
        run: echo "Notion Token is ${{ secrets.NOTION_TOKEN }}"
      - name: Test NOTION_TOKEN Secret
        run: echo "Notion Token is ${{ vars.ANTONVAR }}"

  deploy-web:
      name: Deploy Web
      runs-on: ubuntu-latest
      environment: Notion
      env:
            FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }} 
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            NOTION_MEMBERS_ID: ${{ secrets.NOTION_MEMBERS_ID }}
            ANTON: ${{ secrets.ANTON }}
            AntonVar: ${{ vars.ANTONVAR }}
      steps:
                            
        - name: actions checkout v3
          uses: actions/checkout@v3

        - name: setup flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: Set Fly.io secrets
          run: 
            flyctl secrets set NOTION_MEMBERS_ID=${{ secrets.NOTION_MEMBERS_ID }} \
                            NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} \
                            ANTON=${{ secrets.ANTON }} -a wdcc-youth-of-orakei-staging

        - name: Fly deploy
          run: flyctl deploy --remote-only --config fly.staging.toml
    

        
     
    
      

